export const INCREMENT_CONUTER = "INCREMENT_CONUTER";
export const DECREMENT_CONUTER = "DECREMENT_CONUTER";
export const COUNTER_ACTION_STARTED = "COUNTER_ACTION_STARTED";
export const COUNTER_ACTION_FINISHED = "COUNTER_ACTION_FINISHED";

